services:
  vendure-server:
    environment:
      NODE_ENV: production
      VENDURE_DB_SYNCHRONIZE: "false"
      VENDURE_DISABLE_TELEMETRY: "true"

  vendure-worker:
    environment:
      NODE_ENV: production
      VENDURE_DB_SYNCHRONIZE: "false"
      VENDURE_DISABLE_TELEMETRY: "true"

  backend-svet:
    environment:
      NODE_ENV: production

  rag-api:
    environment:
      PYTHONUNBUFFERED: "1"

  frontend:
    ports:
      - "80:80"
