const timestamp = () => new Date().toISOString();

export const shopCategories = [
  {
    id: 'salniki',
    title: 'Сальники',
    slug: 'salniki',
    description: 'Сальники для стиральных машин, насосов, редукторов и бытовой техники с подбором по размеру.',
    image: 'https://via.placeholder.com/520x360?text=Salniki',
    sortOrder: 10,
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'podshipniki',
    title: 'Подшипники',
    slug: 'podshipniki',
    description: 'Шариковые подшипники для барабанов, двигателей, роликов и ремонтных комплектов.',
    image: 'https://via.placeholder.com/520x360?text=Podshipniki',
    sortOrder: 20,
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'remni',
    title: 'Ремни',
    slug: 'remni',
    description: 'Приводные ремни для стиральных, сушильных и кухонных машин с подбором по маркировке.',
    image: 'https://via.placeholder.com/520x360?text=Remni',
    sortOrder: 30,
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'manzhety',
    title: 'Манжеты',
    slug: 'manzhety',
    description: 'Манжеты люка, уплотнительные кольца и резиновые элементы для ремонта бытовой техники.',
    image: 'https://via.placeholder.com/520x360?text=Manzhety',
    sortOrder: 40,
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'prokladki',
    title: 'Прокладки',
    slug: 'prokladki',
    description: 'Прокладки насосов, патрубков, клапанов, бойлеров и холодильных контуров.',
    image: 'https://via.placeholder.com/520x360?text=Prokladki',
    sortOrder: 50,
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'zapchasti-stiralnyh-mashin',
    title: 'Запчасти для стиральных машин',
    slug: 'zapchasti-dlya-stiralnyh-mashin',
    description: 'Насосы, ТЭНы, амортизаторы, фильтры, щётки и комплектующие для стиральных машин.',
    image: 'https://via.placeholder.com/520x360?text=Stiralnye+mashiny',
    sortOrder: 60,
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'zapchasti-holodilnikov',
    title: 'Запчасти для холодильников',
    slug: 'zapchasti-dlya-holodilnikov',
    description: 'Уплотнители, термостаты, реле, вентиляторы и расходники для холодильников.',
    image: 'https://via.placeholder.com/520x360?text=Holodilniki',
    sortOrder: 70,
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'rashodniki-i-krepezh',
    title: 'Расходники и крепёж',
    slug: 'raskhodniki-i-krepezh',
    description: 'Хомуты, смазка, герметики, фильтры и мелкие расходные материалы для ремонта.',
    image: 'https://via.placeholder.com/520x360?text=Rashodniki',
    sortOrder: 80,
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
];

export const shopProducts = [
  {
    id: 'salnik-35x62x10-nbr',
    categoryId: 'salniki',
    title: 'Сальник 35x62x10 NBR',
    slug: 'salnik-35x62x10-nbr',
    sku: 'SL-356210-NBR',
    price: 2300,
    oldPrice: 2900,
    currency: 'KZT',
    inStock: true,
    stockQty: 56,
    brand: 'SealPro',
    size: '35x62x10',
    applianceType: 'Стиральная машина',
    material: 'NBR',
    description: 'Популярный сальник бака стиральной машины для ремонта узла барабана и защиты подшипников от влаги.',
    specs: {
      'Внутренний диаметр': '35 мм',
      'Внешний диаметр': '62 мм',
      Толщина: '10 мм',
      Материал: 'NBR',
    },
    compatibility: ['LG', 'Samsung', 'Whirlpool'],
    analogs: ['salnik-37x66x9-5-nbr', 'salnik-baka-40x72x10-nbr'],
    tags: ['сальник', '35x62x10', 'бак', 'стиральная машина'],
    images: ['https://via.placeholder.com/520x360?text=Salnik+35x62x10'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'salnik-25x47x10-nbr',
    categoryId: 'salniki',
    title: 'Сальник 25x47x10 NBR',
    slug: 'salnik-25x47x10-nbr',
    sku: 'SL-254710-NBR',
    price: 1900,
    currency: 'KZT',
    inStock: true,
    stockQty: 38,
    brand: 'AquaSeal',
    size: '25x47x10',
    applianceType: 'Стиральная машина',
    material: 'NBR',
    description: 'Сальник для посадки на вал стиральной машины, подходит для стандартных ремонтных комплектов.',
    specs: {
      'Внутренний диаметр': '25 мм',
      'Внешний диаметр': '47 мм',
      Толщина: '10 мм',
      Материал: 'NBR',
    },
    compatibility: ['Bosch', 'Indesit', 'Ariston'],
    analogs: ['salnik-30x52x10-nbr'],
    tags: ['сальник', '25x47x10', 'ремкомплект'],
    images: ['https://via.placeholder.com/520x360?text=Salnik+25x47x10'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'salnik-30x52x10-nbr',
    categoryId: 'salniki',
    title: 'Сальник 30x52x10 NBR',
    slug: 'salnik-30x52x10-nbr',
    sku: 'SL-305210-NBR',
    price: 2100,
    currency: 'KZT',
    inStock: true,
    stockQty: 31,
    brand: 'SealPro',
    size: '30x52x10',
    applianceType: 'Стиральная машина',
    material: 'NBR',
    description: 'Уплотнение для барабанного узла, часто используется вместе с подшипниками серии 6204/6205.',
    specs: {
      'Внутренний диаметр': '30 мм',
      'Внешний диаметр': '52 мм',
      Толщина: '10 мм',
      Материал: 'NBR',
    },
    compatibility: ['Beko', 'Candy', 'Vestel'],
    analogs: ['salnik-25x47x10-nbr', 'salnik-35x62x10-nbr'],
    tags: ['сальник', '30x52x10', 'подбор по размеру'],
    images: ['https://via.placeholder.com/520x360?text=Salnik+30x52x10'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'salnik-37x66x9-5-nbr',
    categoryId: 'salniki',
    title: 'Сальник 37x66x9.5 NBR',
    slug: 'salnik-37x66x9-5-nbr',
    sku: 'SL-376695-NBR',
    price: 2450,
    currency: 'KZT',
    inStock: false,
    stockQty: 0,
    brand: 'AquaGuard',
    size: '37x66x9.5',
    applianceType: 'Стиральная машина',
    material: 'NBR',
    description: 'Сальник под заказ для барабанных узлов, доступен подбор аналога по валу и посадочному месту.',
    specs: {
      'Внутренний диаметр': '37 мм',
      'Внешний диаметр': '66 мм',
      Толщина: '9.5 мм',
      Материал: 'NBR',
    },
    compatibility: ['Electrolux', 'Zanussi', 'AEG'],
    analogs: ['salnik-35x62x10-nbr', 'salnik-baka-40x72x10-nbr'],
    tags: ['сальник', '37x66x9.5', 'под заказ'],
    images: ['https://via.placeholder.com/520x360?text=Salnik+37x66x9.5'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'salnik-40x72x10-nbr',
    categoryId: 'salniki',
    title: 'Сальник бака 40x72x10 NBR',
    slug: 'salnik-baka-40x72x10-nbr',
    sku: 'SL-407210-NBR',
    price: 2600,
    currency: 'KZT',
    inStock: true,
    stockQty: 18,
    brand: 'AquaGuard',
    size: '40x72x10',
    applianceType: 'Стиральная машина',
    material: 'NBR',
    description: 'Сальник бака для узлов с увеличенным посадочным диаметром, используется при капитальном ремонте барабана.',
    specs: {
      'Внутренний диаметр': '40 мм',
      'Внешний диаметр': '72 мм',
      Толщина: '10 мм',
      Материал: 'NBR',
    },
    compatibility: ['LG', 'Samsung', 'Electrolux'],
    analogs: ['salnik-35x62x10-nbr', 'salnik-37x66x9-5-nbr'],
    tags: ['сальник', 'бак', '40x72x10'],
    images: ['https://via.placeholder.com/520x360?text=Salnik+40x72x10'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'podshipnik-6204-2rs',
    categoryId: 'podshipniki',
    title: 'Подшипник 6204 2RS',
    slug: 'podshipnik-6204-2rs',
    sku: 'BR-6204-2RS',
    price: 1800,
    currency: 'KZT',
    inStock: true,
    stockQty: 44,
    brand: 'SKF',
    size: '20x47x14',
    applianceType: 'Стиральная машина',
    material: 'Сталь',
    description: 'Закрытый шариковый подшипник для барабанов, двигателей и роликов бытовой техники.',
    specs: {
      'Внутренний диаметр': '20 мм',
      'Внешний диаметр': '47 мм',
      Ширина: '14 мм',
      Тип: '2RS',
    },
    compatibility: ['LG', 'Samsung', 'Beko'],
    analogs: ['podshipnik-6205-2rs', 'podshipnik-6203-2rs'],
    tags: ['подшипник', '6204', '2RS', 'стиральная машина'],
    images: ['https://via.placeholder.com/520x360?text=Podshipnik+6204'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'podshipnik-6205-2rs',
    categoryId: 'podshipniki',
    title: 'Подшипник 6205 2RS',
    slug: 'podshipnik-6205-2rs',
    sku: 'BR-6205-2RS',
    price: 2200,
    currency: 'KZT',
    inStock: true,
    stockQty: 27,
    brand: 'NTN',
    size: '25x52x15',
    applianceType: 'Стиральная машина',
    material: 'Сталь',
    description: 'Подшипник для барабанных узлов и приводных механизмов, часто ставится парой с 6204.',
    specs: {
      'Внутренний диаметр': '25 мм',
      'Внешний диаметр': '52 мм',
      Ширина: '15 мм',
      Тип: '2RS',
    },
    compatibility: ['Indesit', 'Ariston', 'Candy'],
    analogs: ['podshipnik-6204-2rs', 'podshipnik-6305-2rs'],
    tags: ['подшипник', '6205', 'ремонт барабана'],
    images: ['https://via.placeholder.com/520x360?text=Podshipnik+6205'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'podshipnik-6203-2rs',
    categoryId: 'podshipniki',
    title: 'Подшипник 6203 2RS',
    slug: 'podshipnik-6203-2rs',
    sku: 'BR-6203-2RS',
    price: 1600,
    currency: 'KZT',
    inStock: true,
    stockQty: 33,
    brand: 'NSK',
    size: '17x40x12',
    applianceType: 'Двигатель / ролик',
    material: 'Сталь',
    description: 'Компактный закрытый подшипник для двигателей, роликов и малых узлов бытовой техники.',
    specs: {
      'Внутренний диаметр': '17 мм',
      'Внешний диаметр': '40 мм',
      Ширина: '12 мм',
      Тип: '2RS',
    },
    compatibility: ['Универсально'],
    analogs: ['podshipnik-6204-2rs'],
    tags: ['подшипник', '6203', 'двигатель'],
    images: ['https://via.placeholder.com/520x360?text=Podshipnik+6203'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'podshipnik-6305-2rs',
    categoryId: 'podshipniki',
    title: 'Подшипник 6305 2RS',
    slug: 'podshipnik-6305-2rs',
    sku: 'BR-6305-2RS',
    price: 3200,
    currency: 'KZT',
    inStock: false,
    stockQty: 0,
    brand: 'KOYO',
    size: '25x62x17',
    applianceType: 'Стиральная машина',
    material: 'Сталь',
    description: 'Усиленный подшипник для нагруженных барабанных узлов, доступен под заказ.',
    specs: {
      'Внутренний диаметр': '25 мм',
      'Внешний диаметр': '62 мм',
      Ширина: '17 мм',
      Тип: '2RS',
    },
    compatibility: ['Уточнить по модели'],
    analogs: ['podshipnik-6205-2rs'],
    tags: ['подшипник', '6305', 'усиленный'],
    images: ['https://via.placeholder.com/520x360?text=Podshipnik+6305'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'remen-1192-j5',
    categoryId: 'remni',
    title: 'Ремень 1192 J5',
    slug: 'remen-1192-j5',
    sku: 'BL-1192-J5',
    price: 4200,
    currency: 'KZT',
    inStock: true,
    stockQty: 22,
    brand: 'Megadyne',
    size: '1192 J5',
    applianceType: 'Стиральная машина',
    material: 'Резина',
    description: 'Приводной поликлиновой ремень для стиральных машин, подбирается по маркировке старого ремня.',
    specs: {
      Длина: '1192 мм',
      Профиль: 'J5',
      Тип: 'Поликлиновой',
      Материал: 'Резина',
    },
    compatibility: ['Samsung', 'LG', 'Bosch'],
    analogs: ['remen-1270-j4', 'remen-1046-h7'],
    tags: ['ремень', '1192 J5', 'приводной'],
    images: ['https://via.placeholder.com/520x360?text=Remen+1192+J5'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'remen-1270-j4',
    categoryId: 'remni',
    title: 'Ремень 1270 J4',
    slug: 'remen-1270-j4',
    sku: 'BL-1270-J4',
    price: 3900,
    currency: 'KZT',
    inStock: true,
    stockQty: 16,
    brand: 'Gates',
    size: '1270 J4',
    applianceType: 'Сушильная машина',
    material: 'Резина',
    description: 'Ремень для сушильных и стиральных машин, подходит для ряда моделей с профилем J4.',
    specs: {
      Длина: '1270 мм',
      Профиль: 'J4',
      Тип: 'Поликлиновой',
      Материал: 'Резина',
    },
    compatibility: ['Beko', 'Candy', 'Whirlpool'],
    analogs: ['remen-1192-j5'],
    tags: ['ремень', '1270 J4', 'сушильная машина'],
    images: ['https://via.placeholder.com/520x360?text=Remen+1270+J4'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'remen-1046-h7',
    categoryId: 'remni',
    title: 'Ремень 1046 H7',
    slug: 'remen-1046-h7',
    sku: 'BL-1046-H7',
    price: 3600,
    currency: 'KZT',
    inStock: false,
    stockQty: 0,
    brand: 'Hutchinson',
    size: '1046 H7',
    applianceType: 'Стиральная машина',
    material: 'Резина',
    description: 'Ремень под заказ для машин с профилем H7, подбирается по маркировке и модели техники.',
    specs: {
      Длина: '1046 мм',
      Профиль: 'H7',
      Тип: 'Поликлиновой',
      Материал: 'Резина',
    },
    compatibility: ['Уточнить по модели'],
    analogs: ['remen-1192-j5'],
    tags: ['ремень', '1046 H7', 'под заказ'],
    images: ['https://via.placeholder.com/520x360?text=Remen+1046+H7'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'manzheta-lyuka-lg-4986er1004a',
    categoryId: 'manzhety',
    title: 'Манжета люка LG 4986ER1004A',
    slug: 'manzheta-lyuka-lg-4986er1004a',
    sku: 'MG-LG-4986ER1004A',
    price: 9800,
    oldPrice: 11200,
    currency: 'KZT',
    inStock: true,
    stockQty: 9,
    brand: 'LG compatible',
    size: '4986ER1004A',
    applianceType: 'Стиральная машина',
    material: 'EPDM',
    description: 'Манжета люка для стиральных машин LG, помогает устранить протечки и износ уплотнения двери.',
    specs: {
      Тип: 'Манжета люка',
      Материал: 'EPDM',
      Цвет: 'Серый',
      'OEM/аналог': '4986ER1004A',
    },
    compatibility: ['LG'],
    analogs: ['manzheta-universal-420'],
    tags: ['манжета', 'люк', 'LG', '4986ER1004A'],
    images: ['https://via.placeholder.com/520x360?text=Manzheta+LG'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'manzheta-universal-420',
    categoryId: 'manzhety',
    title: 'Манжета люка универсальная 420 мм',
    slug: 'manzheta-lyuka-universalnaya-420-mm',
    sku: 'MG-UNI-420',
    price: 7200,
    currency: 'KZT',
    inStock: true,
    stockQty: 14,
    brand: 'AquaSeal',
    size: '420 мм',
    applianceType: 'Стиральная машина',
    material: 'EPDM',
    description: 'Универсальная манжета люка для подбора по посадочному диаметру и форме патрубка.',
    specs: {
      Диаметр: '420 мм',
      Материал: 'EPDM',
      Цвет: 'Серый',
      Подбор: 'По фото и модели',
    },
    compatibility: ['Bosch', 'Siemens', 'Electrolux'],
    analogs: ['manzheta-lyuka-lg-4986er1004a'],
    tags: ['манжета', 'универсальная', 'люк'],
    images: ['https://via.placeholder.com/520x360?text=Manzheta+420'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'prokladka-nasosa-40x50',
    categoryId: 'prokladki',
    title: 'Прокладка насоса 40x50',
    slug: 'prokladka-nasosa-40x50',
    sku: 'GK-PUMP-4050',
    price: 900,
    currency: 'KZT',
    inStock: true,
    stockQty: 75,
    brand: 'SealTech',
    size: '40x50',
    applianceType: 'Стиральная машина',
    material: 'NBR',
    description: 'Прокладка для сливного насоса и патрубков, используется при устранении протечек.',
    specs: {
      'Внутренний диаметр': '40 мм',
      'Внешний диаметр': '50 мм',
      Толщина: '5 мм',
      Материал: 'NBR',
    },
    compatibility: ['Whirlpool', 'Candy', 'Beko'],
    analogs: ['prokladka-klapana-18x24'],
    tags: ['прокладка', 'насос', '40x50'],
    images: ['https://via.placeholder.com/520x360?text=Prokladka+nasosa'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'prokladka-klapana-18x24',
    categoryId: 'prokladki',
    title: 'Прокладка клапана 18x24',
    slug: 'prokladka-klapana-18x24',
    sku: 'GK-VALVE-1824',
    price: 650,
    currency: 'KZT',
    inStock: true,
    stockQty: 84,
    brand: 'SealTech',
    size: '18x24',
    applianceType: 'Стиральная / посудомоечная машина',
    material: 'Силикон',
    description: 'Силиконовая прокладка для клапанов и соединений малого диаметра.',
    specs: {
      'Внутренний диаметр': '18 мм',
      'Внешний диаметр': '24 мм',
      Материал: 'Силикон',
      Назначение: 'Клапан / штуцер',
    },
    compatibility: ['Универсально'],
    analogs: ['prokladka-nasosa-40x50'],
    tags: ['прокладка', 'клапан', 'силикон'],
    images: ['https://via.placeholder.com/520x360?text=Prokladka+18x24'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'nasos-slivnoy-askoll-40w',
    categoryId: 'zapchasti-stiralnyh-mashin',
    title: 'Насос сливной Askoll 40W',
    slug: 'nasos-slivnoy-askoll-40w',
    sku: 'WP-ASKOLL-40W',
    price: 5900,
    currency: 'KZT',
    inStock: true,
    stockQty: 21,
    brand: 'Askoll',
    size: '40W',
    applianceType: 'Стиральная машина',
    material: 'Пластик / медь',
    description: 'Сливной насос для стиральной машины, подходит для замены помпы при слабом сливе или шуме.',
    specs: {
      Мощность: '40 Вт',
      Напряжение: '220-240 В',
      Тип: 'Сливной насос',
      Крепление: '3 винта',
    },
    compatibility: ['Bosch', 'Vestel', 'Ariston'],
    analogs: ['filtr-slivnogo-nasosa'],
    tags: ['насос', 'помпа', 'сливной', 'Askoll'],
    images: ['https://via.placeholder.com/520x360?text=Nasos+Askoll'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'ten-1800w-s-datchikom',
    categoryId: 'zapchasti-stiralnyh-mashin',
    title: 'ТЭН 1800W с отверстием под датчик',
    slug: 'ten-1800w-s-datchikom',
    sku: 'HE-1800-SENSOR',
    price: 8500,
    oldPrice: 9200,
    currency: 'KZT',
    inStock: true,
    stockQty: 14,
    brand: 'ThermoPro',
    size: '1800W',
    applianceType: 'Стиральная машина',
    material: 'Нержавеющая сталь',
    description: 'Нагревательный элемент для стиральных машин с посадкой под температурный датчик.',
    specs: {
      Мощность: '1800 Вт',
      Напряжение: '220 В',
      'Отверстие под датчик': 'Есть',
      Материал: 'Нержавеющая сталь',
    },
    compatibility: ['Indesit', 'Ariston', 'Samsung'],
    analogs: ['ten-2000w-bez-datchika'],
    tags: ['ТЭН', 'нагреватель', '1800W'],
    images: ['https://via.placeholder.com/520x360?text=TEN+1800W'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'ten-2000w-bez-datchika',
    categoryId: 'zapchasti-stiralnyh-mashin',
    title: 'ТЭН 2000W без датчика',
    slug: 'ten-2000w-bez-datchika',
    sku: 'HE-2000-NO-SENSOR',
    price: 7900,
    currency: 'KZT',
    inStock: false,
    stockQty: 0,
    brand: 'ThermoPro',
    size: '2000W',
    applianceType: 'Стиральная машина',
    material: 'Нержавеющая сталь',
    description: 'Нагреватель под заказ для моделей, где температурный датчик установлен отдельно.',
    specs: {
      Мощность: '2000 Вт',
      Напряжение: '220 В',
      'Отверстие под датчик': 'Нет',
      Материал: 'Нержавеющая сталь',
    },
    compatibility: ['Уточнить по модели'],
    analogs: ['ten-1800w-s-datchikom'],
    tags: ['ТЭН', '2000W', 'под заказ'],
    images: ['https://via.placeholder.com/520x360?text=TEN+2000W'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'amortizator-100n',
    categoryId: 'zapchasti-stiralnyh-mashin',
    title: 'Амортизатор 100N',
    slug: 'amortizator-100n',
    sku: 'AM-100N',
    price: 3400,
    currency: 'KZT',
    inStock: true,
    stockQty: 26,
    brand: 'ShockPro',
    size: '100N',
    applianceType: 'Стиральная машина',
    material: 'Металл / пластик',
    description: 'Амортизатор для снижения вибрации бака стиральной машины, продаётся поштучно.',
    specs: {
      Усилие: '100N',
      Длина: '185-260 мм',
      Тип: 'Фрикционный',
      Комплектация: '1 шт',
    },
    compatibility: ['Samsung', 'LG', 'Beko'],
    analogs: ['amortizator-120n'],
    tags: ['амортизатор', '100N', 'вибрация'],
    images: ['https://via.placeholder.com/520x360?text=Amortizator+100N'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'amortizator-120n',
    categoryId: 'zapchasti-stiralnyh-mashin',
    title: 'Амортизатор 120N',
    slug: 'amortizator-120n',
    sku: 'AM-120N',
    price: 3700,
    currency: 'KZT',
    inStock: true,
    stockQty: 18,
    brand: 'ShockPro',
    size: '120N',
    applianceType: 'Стиральная машина',
    material: 'Металл / пластик',
    description: 'Усиленный амортизатор для машин с повышенной загрузкой и сильной вибрацией.',
    specs: {
      Усилие: '120N',
      Длина: '185-260 мм',
      Тип: 'Фрикционный',
      Комплектация: '1 шт',
    },
    compatibility: ['LG', 'Samsung', 'Indesit'],
    analogs: ['amortizator-100n'],
    tags: ['амортизатор', '120N', 'усиленный'],
    images: ['https://via.placeholder.com/520x360?text=Amortizator+120N'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'filtr-slivnogo-nasosa',
    categoryId: 'zapchasti-stiralnyh-mashin',
    title: 'Фильтр сливного насоса',
    slug: 'filtr-slivnogo-nasosa',
    sku: 'FL-PUMP-UNI',
    price: 2500,
    currency: 'KZT',
    inStock: true,
    stockQty: 36,
    brand: 'Universal',
    size: 'Универсальный',
    applianceType: 'Стиральная машина',
    material: 'Пластик',
    description: 'Фильтр сливного насоса с крышкой для замены повреждённого или утерянного элемента.',
    specs: {
      Тип: 'Фильтр насоса',
      Материал: 'Пластик',
      Подбор: 'По фото старого фильтра',
      Цвет: 'Белый / серый',
    },
    compatibility: ['Уточнить по фото'],
    analogs: ['nasos-slivnoy-askoll-40w'],
    tags: ['фильтр', 'насос', 'слив'],
    images: ['https://via.placeholder.com/520x360?text=Filtr+nasosa'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'uplotnitel-dveri-holodilnika-57x83',
    categoryId: 'zapchasti-holodilnikov',
    title: 'Уплотнитель двери холодильника 57x83',
    slug: 'uplotnitel-dveri-holodilnika-57x83',
    sku: 'FR-SEAL-5783',
    price: 6200,
    currency: 'KZT',
    inStock: true,
    stockQty: 12,
    brand: 'CoolSeal',
    size: '57x83 см',
    applianceType: 'Холодильник',
    material: 'ПВХ / магнитная вставка',
    description: 'Магнитный уплотнитель двери холодильника для восстановления герметичности камеры.',
    specs: {
      Размер: '57x83 см',
      Тип: 'Магнитный',
      Материал: 'ПВХ',
      Цвет: 'Белый',
    },
    compatibility: ['Уточнить по модели холодильника'],
    analogs: ['termostat-holodilnika-k59'],
    tags: ['уплотнитель', 'холодильник', 'дверь'],
    images: ['https://via.placeholder.com/520x360?text=Uplotnitel+holodilnika'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'termostat-holodilnika-k59',
    categoryId: 'zapchasti-holodilnikov',
    title: 'Термостат холодильника K59',
    slug: 'termostat-holodilnika-k59',
    sku: 'FR-THERMO-K59',
    price: 4800,
    currency: 'KZT',
    inStock: true,
    stockQty: 17,
    brand: 'Ranco compatible',
    size: 'K59',
    applianceType: 'Холодильник',
    material: 'Металл / пластик',
    description: 'Термостат K59 для регулировки температуры в холодильниках и морозильных камерах.',
    specs: {
      Модель: 'K59',
      Тип: 'Механический',
      Назначение: 'Холодильник',
      Подключение: 'Клеммы',
    },
    compatibility: ['Atlant', 'Indesit', 'Бирюса'],
    analogs: ['uplotnitel-dveri-holodilnika-57x83'],
    tags: ['термостат', 'K59', 'холодильник'],
    images: ['https://via.placeholder.com/520x360?text=Termostat+K59'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'smazka-dlya-salnikov-50g',
    categoryId: 'rashodniki-i-krepezh',
    title: 'Смазка для сальников 50 г',
    slug: 'smazka-dlya-salnikov-50g',
    sku: 'CN-GREASE-50',
    price: 1700,
    currency: 'KZT',
    inStock: true,
    stockQty: 64,
    brand: 'ServiceKit',
    size: '50 г',
    applianceType: 'Ремонт бытовой техники',
    material: 'Водостойкая смазка',
    description: 'Водостойкая смазка для установки сальников и защиты рабочей кромки от сухого хода.',
    specs: {
      Объём: '50 г',
      Тип: 'Водостойкая',
      Назначение: 'Сальники / подшипниковый узел',
      Температура: 'до 120 C',
    },
    compatibility: ['Универсально'],
    analogs: ['homut-chervyachnyy-20-32'],
    tags: ['смазка', 'сальник', 'ремонт'],
    images: ['https://via.placeholder.com/520x360?text=Smazka+50g'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
  {
    id: 'homut-chervyachnyy-20-32',
    categoryId: 'rashodniki-i-krepezh',
    title: 'Хомут червячный 20-32 мм',
    slug: 'homut-chervyachnyy-20-32-mm',
    sku: 'CN-CLAMP-2032',
    price: 350,
    currency: 'KZT',
    inStock: true,
    stockQty: 120,
    brand: 'ServiceKit',
    size: '20-32 мм',
    applianceType: 'Ремонт бытовой техники',
    material: 'Оцинкованная сталь',
    description: 'Хомут для патрубков и шлангов при ремонте стиральных и посудомоечных машин.',
    specs: {
      Диапазон: '20-32 мм',
      Тип: 'Червячный',
      Материал: 'Оцинкованная сталь',
      Назначение: 'Патрубки / шланги',
    },
    compatibility: ['Универсально'],
    analogs: ['smazka-dlya-salnikov-50g'],
    tags: ['хомут', 'крепёж', 'шланг'],
    images: ['https://via.placeholder.com/520x360?text=Homut+20-32'],
    isActive: true,
    createdAt: timestamp(),
    updatedAt: timestamp(),
  },
];
